ci: simple assertion

diff --git a/.github/workflows/docker-test.yaml b/.github/workflows/docker-test.yaml
--- a/.github/workflows/docker-test.yaml
+++ b/.github/workflows/docker-test.yaml
@@ -81,28 +81,7 @@ jobs:
     name: All acceptance tests complete
     runs-on: ubuntu-latest
     steps:
-      - name: Check test suites
-        shell: bash
+      - name: Assert no failures
         env:
-          NEEDS: ${{ needs }}
-          FAILURE_MSG: Acceptance tests failed
-          SUCCESS_MSG: Acceptance tests succeeded
-        run: |
-          set -euo pipefail
-
-          # Print the needs context, debugging
-          echo "$NEEDS" | jq
-
-          # Extract failures
-          FAILURES="$(echo "$NEEDS" | jq 'with_entries(select(.value.result == "failure")) | map_values(.result)')"
-
-          # Check if there are any failures
-          if [ "$(echo "$FAILURES" | jq '. | length')" != "0" ]; then
-            echo "❌ $FAILURE_MSG"
-            echo "Failed suites:"
-            echo "$FAILURES" | jq -r 'to_entries[] | "- \(.key): \(.value)"'
-            echo "any-failed=true" >> "$GITHUB_OUTPUT"
-            exit 1
-          fi
-
-          echo "✅ $SUCCESS_MSG"
+          NEEDS: ${{ toJson(needs) }}
+        run: exit $(echo "$NEEDS" | jq 'with_entries(select(.value.result == "failure")) | length')
